trigger: 
 - main 
pool: omkar-hcl
stages: 
 - stage: terraform_init
   displayName: terraform init & plan
   jobs:
   - job: terraforminstall
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         backendServiceArm: 'HCL-infrasc'
         backendAzureRmStorageAccountName: 'hclsa45623'
         backendAzureRmContainerName: 'tfstate'
         backendAzureRmKey: 'prod.terraform.tfstate'
         workingDirectory: '$(Build.SourcesDirectory)/omkar/parent'

