trigger: 
 - main 
pool: omkar-hcl
stages: 
 - stage: terraform_init
   displayName: terraform init & plan
   jobs:
   - job: terraforminstall
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'

