trigger:
  - main

pool: omkar-hcl


stages:
- stage: terraform_init_plan
  displayName: Terraform Init, Format, Validate, Plan
  jobs:
  - job: terraform_job
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'HCL-infrasc'
        backendAzureRmStorageAccountName: 'hclsa45623'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'
        workingDirectory: '$(Build.SourcesDirectory)/omkar/parent'
      displayName: Terraform Init



    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/omkar/parent'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'HCL-infrasc'
        
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/omkar/parent'


    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/omkar/parent'
        environmentServiceNameAzureRM: 'HCL-infrasc'

- stage: terraform_security_scan
  dependsOn: terraform_init_plan
  jobs:
  - job: security_scan_job
    pool: omkar-hcl
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        debug: true

    # tfsec install and run
    - script: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash
        ./tfsec $(System.DefaultWorkingDirectory)/omkar/parent
      displayName: Run tfsec scan

    # tflint install and run
    - script: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint $(System.DefaultWorkingDirectory)/omkar/parent
      displayName: Run tflint scan

    # checkov install and run
    - script: |
        pip install checkov
        checkov -d $(System.DefaultWorkingDirectory)/omkar/parent
      displayName: Run checkov scan