trigger:
  - main

pool: omkar-hcl


stages:
- stage: terraform_init_plan
  displayName: Terraform Init, Format, Validate, Plan
  jobs:
  - job: terraform_job
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'HCL-infrasc'
        backendAzureRmStorageAccountName: 'hclsa45623'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'
        workingDirectory: '$(Build.SourcesDirectory)/omkar/parent'
      displayName: Terraform Init

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/omkar/parent'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'HCL-infrasc'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(Build.SourcesDirectory)/omkar/parent'
      displayName: Terraform Validate

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Build.SourcesDirectory)/omkar/parent'
        environmentServiceNameAzureRM: 'HCL-infrasc'
        ensureBackend: true
        backendAzureRmStorageAccountName: 'hclsa45623'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'
      displayName: Terraform Plan

 