trigger:
  - main

pool: omkar-hcl

parameters:
  - name: terraformVersion
    type: string
    default: '1.5.7'

  - name: terraformDir
    type: string
    default: '$(Build.SourcesDirectory)/omkar/parent'

stages:
# ------------------------------------------------------
# Stage 1: Install Terraform & Publish Artifact
# ------------------------------------------------------
- stage: terraform_init
  displayName: Terraform Install
  jobs:
  - job: terraforminstall
    steps:
    - checkout: self

    - script: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/${{ parameters.terraformVersion }}/terraform_${{ parameters.terraformVersion }}_linux_amd64.zip
        unzip terraform.zip
        mkdir -p $(Build.ArtifactStagingDirectory)/terraform-bin
        mv terraform $(Build.ArtifactStagingDirectory)/terraform-bin/
      displayName: Download & Extract Terraform

    - publish: $(Build.ArtifactStagingDirectory)/terraform-bin
      artifact: terraform-bin

# ------------------------------------------------------
# Stage 2: Download Artifact & Run Terraform Init
# ------------------------------------------------------
- stage: terraformin
  displayName: Terraform Init & Plan
  dependsOn: terraform_init
  jobs:
  - job: terraforminit
    steps:
    - checkout: self

    - download: current
      artifact: terraform-bin

    - script: |
        chmod +x $(Pipeline.Workspace)/terraform-bin/terraform
        export PATH=$(Pipeline.Workspace)/terraform-bin:$PATH
        terraform version
        terraform init \
          -backend-config="storage_account_name=hclsa45623" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=prod.terraform.tfstate" \
          -backend-config="resource_group_name=HCL-infrasc"
      workingDirectory: '${{ parameters.terraformDir }}'
      displayName: Terraform Init


