trigger: 
 - main 
pool: omkar-hcl
stages: 
 - stage: terraform_init
   displayName: terraform init & plan
   jobs:
   - job: terraforminstall
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
   - job: terraforminit
     steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         backendServiceArm: 'HCL-infrasc'
         backendAzureRmStorageAccountName: 'hclsa45623'
         backendAzureRmContainerName: 'tfstate'
         backendAzureRmKey: 'prod.terraform.tfstate'
         workingDirectory: 'C:\Users\OMKAR SINGH\OneDrive\Documents\Downloads\azure document sof\vsts-agent-win-x64-4.260.0\_work\4\s\omkar'

